services:
  user-service:
    build:
      context: ./
      dockerfile: User-Service/Dockerfile
    image: user-service:1.0.0
    expose:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/${DB_NAME}
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: '2'
          memory: 512M
        reservations:
          cpus: '1'
          memory: 256M


  list-service:
    build: 
      context: ./
      dockerfile: List-Service/Dockerfile
    image: list-service:1.0.0
    expose:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/${DB_NAME}
    env_file:
      - .env
    hostname: "{{.Service.Name}-{.Task.Slot}}"
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: '2'
          memory: 512M
        reservations:
          cpus: '1'
          memory: 256M


  frontend-service:
    build: 
      context: ./
      dockerfile: Frontend/dockerfile
    image: frontend-service:1.0.0
    ports:
      - "5500:4200"
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 512M
        reservations:
          cpus: '1'
          memory: 256M


  server:
    build:
      context: ./
      dockerfile: Server/Dockerfile
    image: server:1.0.0
    ports:
      - "8080"
    environment:
      - SPRING_REDIS_HOST=sessionRedis
      - SPRING_REDIS_PORT=7000
    env_file:
      - .env
    hostname: "{{.Service.Name}-{.Task.Slot}}"
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: '2'
          memory: 512M
        reservations:
          cpus: '1'
          memory: 256M


  mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_DATABASE=${DB_NAME}'
      - 'MARIADB_PASSWORD=${DB_PASSWORD}'
      - 'MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
      - 'MARIADB_USER=${DB_USERNAME}'
    ports:
      - '3306'
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3


  sessionRedis:
    image: redis:latest
    ports:
      - "7000:6379"
    restart: unless-stopped


  load-balancer:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:z
    depends_on:
      - user-service
      - list-service
      - kafka_one
      - kafka_two
      - kafka_three
      - server
    ports:
      - "5000:5000"


  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka_one:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka_one
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_one:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    depends_on:
      - zookeeper

  kafka_two:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka_two
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_two:9093
    depends_on:
      - zookeeper

  kafka_three:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka_three
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_three:9094
    depends_on:
      - zookeeper