FROM maven:3.9.9-eclipse-temurin-21-alpine AS build

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests

FROM openjdk:21-jdk-slim AS final

WORKDIR /app

COPY --from=build /app/target/messaging-stomp-websocket-1.jar /app

RUN chmod +r /app/messaging-stomp-websocket-1.jar

ENTRYPOINT ["java", "-jar", "/app/messaging-stomp-websocket-1.jar"]
